### ISSUE TITLE
Code and Data

### ISSUE THREAD

**Issue by Liebeck** [IBM/WordMoversEmbeddings#1]
Hi, I'd very much like to benchmark the word mover embeddings but the repository seems to be empty. Would you mind uploading the code?

**Comment by Joey-Liu** [comment]
The code is still not available?

**Comment by Liebeck** [comment]
@Joey-Liu I emailed Teddy a couple of days ago but didn't get any response so far. Maybe he's on vacation without an out-of-office message?

**Comment by dancing-with-coffee** [comment]
I really hope this code will be uploaded ASAP. I also interested in WME and desire to check its efficiency.

**Comment by Liebeck** [comment]
I just e-mailed all co-authors in the hope of getting a reponse. Also highlighting @stevemart

**Comment by Liebeck** [comment]
Teddy answered me that he will upload the code and data in two days =)

**Comment by dancing-with-coffee** [comment]
> Teddy answered me that he will upload the code and data in two days =)


> Teddy answered me that he will upload the code and data in two days =)

I really appreciate your effort! Thanks a lot :)

**Comment by DennisChen0307** [comment]
> Teddy answered me that he will upload the code and data in two days =)

So it is today?

**Comment by teddylfwu** [comment]
Hi Guys, 

Sorry for the long delay. Yes, the codes and data will be uploaded shortly.

**Comment by teddylfwu** [comment]
Codes and data have been pushed into the repo. 

Thanks for your great patience and interests in our work!
